Dev windows konon1337
cpp-park-vk-education/2023_1_C-- pull request #1
Opened 2023-04-28 17:06 UTC by WindowsKonon1337

2023-04-29 16:15 UTC, GeorgiyX requested changes

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IHttpRequest.hpp
> +    virtual std::string getBody() const = 0;
Лучше для представления бинарных данные использовать `std::vector<uint8_t>`

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IHttpRequestHandler.hpp
> +using Shared = std::shared_ptr<T>;
Кажется, что выгоды от такого переопределения типа особо нет. С точки зрения читающего код это все тот же shared_ptr, требующий указания шаблонного параметра.

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IClientDbManager.hpp
> +class IClientDbManager : public IDbManager
Если правильно понимаю и IDbManager это обертка над драйвером БД, то его нужно делать полем в каждом "NameDbManager" (репозитории), т.к. за интерфейсом `IDbManager` скрывается внешняя зависимость.

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IRoomDbManager.hpp
> +    virtual void insertRoom(const std::string&) = 0; // Предполагается, что будет передан JSON с описанием комнаты
JSON нужно распарсить на слое с хендлерами, а в слой с "репозиторяими" нужно передавать готовую структуру с полями сущности `Room`.

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IClientDbManager.hpp
> +class IClientDbManager : public IDbManager
Стоит сгруппировать файлы в в директории `server/include` , например по слоям или про эндпоинтам.

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IHttpRequest.hpp
> +    virtual int getStatus() const = 0;
У запроса нет статуса

2023-04-29 16:15 UTC, GeorgiyX commented on server/include/IHttpRequest.hpp
> +    virtual std::string getHeader() const = 0;
Хедеров может быть несколько.  Можно использовать `std::map<std::string, std::string>` (ключ мапы - имя хедера, значение для ключа - значение хедера).

2023-04-29 16:15 UTC, GeorgiyX commented on tests/server/tests.cpp
> +
Тут не хватает вызова метода который принимает мок и который ты хочешь протестировать.

Можно проверить, что хендлер вызывает `getPath()` у `HttpRequestMock` объекта, затем вызывает слой ниже (будет нужен мок такого слоя).

2023-04-29 16:15 UTC, GeorgiyX commented on tests/server/tests.cpp
> +    EXPECT_EQ(request.getMethod(), HttpMethods::POST);
Похоже ты тут тестируешь правильно ли работает `HttpResponseMock`, а нужно с помощью мока проверить как работает код использующий мок.

2023-04-29 16:15 UTC, GeorgiyX commented on tests/server/tests.cpp
> +    requestMapper.service(&httpRequest, &httpResponse);
С помощью `HttpRequestMock` и `HttpResponseMock` ты можешь проверить имплементацию `IHttpRequestHandler` - т.е. ты тут должен вызывать на пример метод service роутера (который имплементит `IHttpRequestHandler`) и проверять в тесте, например:
1. Роутер запишет код 404 если не найдет нужный обработчик
2. Вызовет нужный обработчик (его можно замокать) и передаст в него `httpResponse` и `httpRequest`.
3. Выбросит исключение если что-то пойдет не так (например `httpRequest` кинет исключение при вызове `getPath`).

2023-05-23 16:01 UTC, ikramichev commented on tests/server/tests.cpp
> +    std::map<std::string, std::unique_ptr<IHttpRequestHandler>> controllers;
Выглядит так, что controllers можно не хранить в качестве поля этого класса. Мы его уже "мувнули", т.е. передали  в функцию по rvalue-ссылке, где эту мапку уже могли теоретически сделать "негодной", например, свопнуть. Плюс к этому controllers напрямую из тестов нигде не вызывается. Можно создать ее в SetUp-е как локальную переменную и не хранить в классе

2023-05-23 16:16 UTC, ikramichev approved these changes

2023-06-04 15:19 UTC, closed without merging